### ISSUE TITLE
YAML file format checker

### ISSUE THREAD

**Issue by DDAZZA** [DDAZZA/renogen#1]
Check YAML files are valid syntax

**Comment by tosch** [comment]
Users should be able to define validation rules for their supported keys for specific headings in their `.renogen` config file. For example:

```yaml
changelog_path: './change_log/'
default_headings:
  - Improvements
  - Minor Improvements
  - Bugs
  - Deploy Tasks
  - Migration Details
  - Dependencies
:rules:
  :*:
    :required_keys:
    - Identifier:
        :format: "/\\w+\\-\\d+/"
    - Title
    - Link:
        :format: URI
    - has_db_change:
        :type: Boolean
    :additional_keys:
    - Description
  Task:
    :required_keys:
    - Command
    :additional_keys:
    - Duration
```

Rules under `*` would apply for all headings, while heading specific rules could be defined additionally.

Those rules could also be used to extend the `new` command:

`renogen new --heading Task ABC-123` could produce the following YAML:
```yaml
Task:
  Identifier:
  Title:
  Link:
  has_db_change: false
  Description:
  Command:
  Duration:
```

What do you think?
